// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: document/document.proto

package document

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query - текст запроса для поиска
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// organization_id - ID организации для фильтрации документов
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// limit - максимальное количество результатов
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// min_score - минимальный порог релевантности (0.0 - 1.0)
	MinScore      float32 `protobuf:"fixed32,4,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChunksRequest) Reset() {
	*x = SearchChunksRequest{}
	mi := &file_document_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChunksRequest) ProtoMessage() {}

func (x *SearchChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChunksRequest.ProtoReflect.Descriptor instead.
func (*SearchChunksRequest) Descriptor() ([]byte, []int) {
	return file_document_document_proto_rawDescGZIP(), []int{0}
}

func (x *SearchChunksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchChunksRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SearchChunksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchChunksRequest) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type SearchChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*DocumentChunk       `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChunksResponse) Reset() {
	*x = SearchChunksResponse{}
	mi := &file_document_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChunksResponse) ProtoMessage() {}

func (x *SearchChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChunksResponse.ProtoReflect.Descriptor instead.
func (*SearchChunksResponse) Descriptor() ([]byte, []int) {
	return file_document_document_proto_rawDescGZIP(), []int{1}
}

func (x *SearchChunksResponse) GetChunks() []*DocumentChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DocumentChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk_id - уникальный ID фрагмента
	ChunkId string `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// document_id - ID исходного документа
	DocumentId string `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// document_name - имя исходного документа
	DocumentName string `protobuf:"bytes,3,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	// content - текстовое содержимое фрагмента
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// position - позиция фрагмента в документе
	Position int32 `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	// score - оценка релевантности (0.0 - 1.0)
	Score float32 `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	// metadata - дополнительные метаданные фрагмента
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_document_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_document_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_document_document_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *DocumentChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentChunk) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *DocumentChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentChunk) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *DocumentChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DocumentChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_document_document_proto protoreflect.FileDescriptor

const file_document_document_proto_rawDesc = "" +
	"\n" +
	"\x17document/document.proto\x12\bdocument\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x87\x01\n" +
	"\x13SearchChunksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tmin_score\x18\x04 \x01(\x02R\bminScore\"G\n" +
	"\x14SearchChunksResponse\x12/\n" +
	"\x06chunks\x18\x01 \x03(\v2\x17.document.DocumentChunkR\x06chunks\"\xbc\x02\n" +
	"\rDocumentChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x03 \x01(\tR\fdocumentName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x02R\x05score\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.document.DocumentChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x81\x01\n" +
	"\x0fDocumentService\x12n\n" +
	"\fSearchChunks\x12\x1d.document.SearchChunksRequest\x1a\x1e.document.SearchChunksResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/documents/searchB\xa7\x01\x92A\x86\x01\x12V\n" +
	"\x17Document Processing API\x124API for Document Processing Service of BusinessThing2\x051.0.0\"\x04/api*\x02\x01\x022\x10application/json:\x10application/jsonZ\x1bdocs-processor/pkg/documentb\x06proto3"

var (
	file_document_document_proto_rawDescOnce sync.Once
	file_document_document_proto_rawDescData []byte
)

func file_document_document_proto_rawDescGZIP() []byte {
	file_document_document_proto_rawDescOnce.Do(func() {
		file_document_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_document_proto_rawDesc), len(file_document_document_proto_rawDesc)))
	})
	return file_document_document_proto_rawDescData
}

var file_document_document_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_document_document_proto_goTypes = []any{
	(*SearchChunksRequest)(nil),  // 0: document.SearchChunksRequest
	(*SearchChunksResponse)(nil), // 1: document.SearchChunksResponse
	(*DocumentChunk)(nil),        // 2: document.DocumentChunk
	nil,                          // 3: document.DocumentChunk.MetadataEntry
}
var file_document_document_proto_depIdxs = []int32{
	2, // 0: document.SearchChunksResponse.chunks:type_name -> document.DocumentChunk
	3, // 1: document.DocumentChunk.metadata:type_name -> document.DocumentChunk.MetadataEntry
	0, // 2: document.DocumentService.SearchChunks:input_type -> document.SearchChunksRequest
	1, // 3: document.DocumentService.SearchChunks:output_type -> document.SearchChunksResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_document_document_proto_init() }
func file_document_document_proto_init() {
	if File_document_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_document_proto_rawDesc), len(file_document_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_document_proto_goTypes,
		DependencyIndexes: file_document_document_proto_depIdxs,
		MessageInfos:      file_document_document_proto_msgTypes,
	}.Build()
	File_document_document_proto = out.File
	file_document_document_proto_goTypes = nil
	file_document_document_proto_depIdxs = nil
}
