// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: document/document.proto

package document

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearchChunksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchChunksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchChunksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchChunksRequestMultiError, or nil if none found.
func (m *SearchChunksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchChunksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Query

	// no validation rules for OrganizationId

	// no validation rules for Limit

	// no validation rules for MinScore

	if len(errors) > 0 {
		return SearchChunksRequestMultiError(errors)
	}

	return nil
}

// SearchChunksRequestMultiError is an error wrapping multiple validation
// errors returned by SearchChunksRequest.ValidateAll() if the designated
// constraints aren't met.
type SearchChunksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchChunksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchChunksRequestMultiError) AllErrors() []error { return m }

// SearchChunksRequestValidationError is the validation error returned by
// SearchChunksRequest.Validate if the designated constraints aren't met.
type SearchChunksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchChunksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchChunksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchChunksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchChunksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchChunksRequestValidationError) ErrorName() string {
	return "SearchChunksRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchChunksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchChunksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchChunksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchChunksRequestValidationError{}

// Validate checks the field values on SearchChunksResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchChunksResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchChunksResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchChunksResponseMultiError, or nil if none found.
func (m *SearchChunksResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchChunksResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetChunks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchChunksResponseValidationError{
						field:  fmt.Sprintf("Chunks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchChunksResponseValidationError{
						field:  fmt.Sprintf("Chunks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchChunksResponseValidationError{
					field:  fmt.Sprintf("Chunks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchChunksResponseMultiError(errors)
	}

	return nil
}

// SearchChunksResponseMultiError is an error wrapping multiple validation
// errors returned by SearchChunksResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchChunksResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchChunksResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchChunksResponseMultiError) AllErrors() []error { return m }

// SearchChunksResponseValidationError is the validation error returned by
// SearchChunksResponse.Validate if the designated constraints aren't met.
type SearchChunksResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchChunksResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchChunksResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchChunksResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchChunksResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchChunksResponseValidationError) ErrorName() string {
	return "SearchChunksResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchChunksResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchChunksResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchChunksResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchChunksResponseValidationError{}

// Validate checks the field values on DocumentChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DocumentChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DocumentChunkMultiError, or
// nil if none found.
func (m *DocumentChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ChunkId

	// no validation rules for DocumentId

	// no validation rules for DocumentName

	// no validation rules for Content

	// no validation rules for Position

	// no validation rules for Score

	// no validation rules for Metadata

	if len(errors) > 0 {
		return DocumentChunkMultiError(errors)
	}

	return nil
}

// DocumentChunkMultiError is an error wrapping multiple validation errors
// returned by DocumentChunk.ValidateAll() if the designated constraints
// aren't met.
type DocumentChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentChunkMultiError) AllErrors() []error { return m }

// DocumentChunkValidationError is the validation error returned by
// DocumentChunk.Validate if the designated constraints aren't met.
type DocumentChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentChunkValidationError) ErrorName() string { return "DocumentChunkValidationError" }

// Error satisfies the builtin error interface
func (e DocumentChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentChunkValidationError{}

// Validate checks the field values on SearchTemplatesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchTemplatesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchTemplatesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchTemplatesRequestMultiError, or nil if none found.
func (m *SearchTemplatesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchTemplatesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Query

	// no validation rules for Limit

	if len(errors) > 0 {
		return SearchTemplatesRequestMultiError(errors)
	}

	return nil
}

// SearchTemplatesRequestMultiError is an error wrapping multiple validation
// errors returned by SearchTemplatesRequest.ValidateAll() if the designated
// constraints aren't met.
type SearchTemplatesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchTemplatesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchTemplatesRequestMultiError) AllErrors() []error { return m }

// SearchTemplatesRequestValidationError is the validation error returned by
// SearchTemplatesRequest.Validate if the designated constraints aren't met.
type SearchTemplatesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchTemplatesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchTemplatesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchTemplatesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchTemplatesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchTemplatesRequestValidationError) ErrorName() string {
	return "SearchTemplatesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchTemplatesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchTemplatesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchTemplatesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchTemplatesRequestValidationError{}

// Validate checks the field values on SearchTemplatesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchTemplatesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchTemplatesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchTemplatesResponseMultiError, or nil if none found.
func (m *SearchTemplatesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchTemplatesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTemplates() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchTemplatesResponseValidationError{
						field:  fmt.Sprintf("Templates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchTemplatesResponseValidationError{
						field:  fmt.Sprintf("Templates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchTemplatesResponseValidationError{
					field:  fmt.Sprintf("Templates[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchTemplatesResponseMultiError(errors)
	}

	return nil
}

// SearchTemplatesResponseMultiError is an error wrapping multiple validation
// errors returned by SearchTemplatesResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchTemplatesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchTemplatesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchTemplatesResponseMultiError) AllErrors() []error { return m }

// SearchTemplatesResponseValidationError is the validation error returned by
// SearchTemplatesResponse.Validate if the designated constraints aren't met.
type SearchTemplatesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchTemplatesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchTemplatesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchTemplatesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchTemplatesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchTemplatesResponseValidationError) ErrorName() string {
	return "SearchTemplatesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchTemplatesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchTemplatesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchTemplatesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchTemplatesResponseValidationError{}

// Validate checks the field values on TemplateSearchResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TemplateSearchResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TemplateSearchResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TemplateSearchResultMultiError, or nil if none found.
func (m *TemplateSearchResult) ValidateAll() error {
	return m.validate(true)
}

func (m *TemplateSearchResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TemplateId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for TemplateType

	// no validation rules for FieldsCount

	// no validation rules for Score

	if len(errors) > 0 {
		return TemplateSearchResultMultiError(errors)
	}

	return nil
}

// TemplateSearchResultMultiError is an error wrapping multiple validation
// errors returned by TemplateSearchResult.ValidateAll() if the designated
// constraints aren't met.
type TemplateSearchResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TemplateSearchResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TemplateSearchResultMultiError) AllErrors() []error { return m }

// TemplateSearchResultValidationError is the validation error returned by
// TemplateSearchResult.Validate if the designated constraints aren't met.
type TemplateSearchResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TemplateSearchResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TemplateSearchResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TemplateSearchResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TemplateSearchResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TemplateSearchResultValidationError) ErrorName() string {
	return "TemplateSearchResultValidationError"
}

// Error satisfies the builtin error interface
func (e TemplateSearchResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTemplateSearchResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TemplateSearchResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TemplateSearchResultValidationError{}
