generate:
	npx swagger-typescript-api@12.0.4 -p ../core-service/pkg/core/core.swagger.json -o ./api -n api.core.generated.ts --axios
	npx swagger-typescript-api@12.0.4 -p https://agent.businessthing.ru/api/swagger -o ./api -n api.agent.generated.ts --axios
	