// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: agent/agent.proto

package agent

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _agent_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Pagination with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Pagination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Pagination with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginationMultiError, or
// nil if none found.
func (m *Pagination) ValidateAll() error {
	return m.validate(true)
}

func (m *Pagination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Page != nil {

		if m.GetPage() <= 0 {
			err := PaginationValidationError{
				field:  "Page",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.PageSize != nil {

		if val := m.GetPageSize(); val <= 0 || val > 100 {
			err := PaginationValidationError{
				field:  "PageSize",
				reason: "value must be inside range (0, 100]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return PaginationMultiError(errors)
	}

	return nil
}

// PaginationMultiError is an error wrapping multiple validation errors
// returned by Pagination.ValidateAll() if the designated constraints aren't met.
type PaginationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginationMultiError) AllErrors() []error { return m }

// PaginationValidationError is the validation error returned by
// Pagination.Validate if the designated constraints aren't met.
type PaginationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationValidationError) ErrorName() string { return "PaginationValidationError" }

// Error satisfies the builtin error interface
func (e PaginationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPagination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationValidationError{}

// Validate checks the field values on GetChatsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetChatsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetChatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetChatsRequestMultiError, or nil if none found.
func (m *GetChatsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetChatsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOrgId()); err != nil {
		err = GetChatsRequestValidationError{
			field:  "OrgId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Pagination != nil {

		if all {
			switch v := interface{}(m.GetPagination()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetChatsRequestValidationError{
						field:  "Pagination",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetChatsRequestValidationError{
						field:  "Pagination",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetChatsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetChatsRequestMultiError(errors)
	}

	return nil
}

func (m *GetChatsRequest) _validateUuid(uuid string) error {
	if matched := _agent_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetChatsRequestMultiError is an error wrapping multiple validation errors
// returned by GetChatsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetChatsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetChatsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetChatsRequestMultiError) AllErrors() []error { return m }

// GetChatsRequestValidationError is the validation error returned by
// GetChatsRequest.Validate if the designated constraints aren't met.
type GetChatsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetChatsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetChatsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetChatsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetChatsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetChatsRequestValidationError) ErrorName() string { return "GetChatsRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetChatsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetChatsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetChatsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetChatsRequestValidationError{}

// Validate checks the field values on GetChatsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetChatsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetChatsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetChatsResponseMultiError, or nil if none found.
func (m *GetChatsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetChatsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetChats() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetChatsResponseValidationError{
						field:  fmt.Sprintf("Chats[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetChatsResponseValidationError{
						field:  fmt.Sprintf("Chats[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetChatsResponseValidationError{
					field:  fmt.Sprintf("Chats[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetChatsResponseMultiError(errors)
	}

	return nil
}

// GetChatsResponseMultiError is an error wrapping multiple validation errors
// returned by GetChatsResponse.ValidateAll() if the designated constraints
// aren't met.
type GetChatsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetChatsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetChatsResponseMultiError) AllErrors() []error { return m }

// GetChatsResponseValidationError is the validation error returned by
// GetChatsResponse.Validate if the designated constraints aren't met.
type GetChatsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetChatsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetChatsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetChatsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetChatsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetChatsResponseValidationError) ErrorName() string { return "GetChatsResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetChatsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetChatsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetChatsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetChatsResponseValidationError{}

// Validate checks the field values on Chat with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Chat) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Chat with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ChatMultiError, or nil if none found.
func (m *Chat) ValidateAll() error {
	return m.validate(true)
}

func (m *Chat) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChatValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChatValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChatValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ChatMultiError(errors)
	}

	return nil
}

// ChatMultiError is an error wrapping multiple validation errors returned by
// Chat.ValidateAll() if the designated constraints aren't met.
type ChatMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatMultiError) AllErrors() []error { return m }

// ChatValidationError is the validation error returned by Chat.Validate if the
// designated constraints aren't met.
type ChatValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatValidationError) ErrorName() string { return "ChatValidationError" }

// Error satisfies the builtin error interface
func (e ChatValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChat.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatValidationError{}

// Validate checks the field values on GetChatRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetChatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetChatRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetChatRequestMultiError,
// or nil if none found.
func (m *GetChatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetChatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetChatId()) < 1 {
		err := GetChatRequestValidationError{
			field:  "ChatId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetChatRequestMultiError(errors)
	}

	return nil
}

// GetChatRequestMultiError is an error wrapping multiple validation errors
// returned by GetChatRequest.ValidateAll() if the designated constraints
// aren't met.
type GetChatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetChatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetChatRequestMultiError) AllErrors() []error { return m }

// GetChatRequestValidationError is the validation error returned by
// GetChatRequest.Validate if the designated constraints aren't met.
type GetChatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetChatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetChatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetChatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetChatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetChatRequestValidationError) ErrorName() string { return "GetChatRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetChatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetChatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetChatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetChatRequestValidationError{}

// Validate checks the field values on GetChatResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetChatResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetChatResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetChatResponseMultiError, or nil if none found.
func (m *GetChatResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetChatResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetChat()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetChatResponseValidationError{
					field:  "Chat",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetChatResponseValidationError{
					field:  "Chat",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChat()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetChatResponseValidationError{
				field:  "Chat",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetChatResponseValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetChatResponseValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetChatResponseValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetChatResponseMultiError(errors)
	}

	return nil
}

// GetChatResponseMultiError is an error wrapping multiple validation errors
// returned by GetChatResponse.ValidateAll() if the designated constraints
// aren't met.
type GetChatResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetChatResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetChatResponseMultiError) AllErrors() []error { return m }

// GetChatResponseValidationError is the validation error returned by
// GetChatResponse.Validate if the designated constraints aren't met.
type GetChatResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetChatResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetChatResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetChatResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetChatResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetChatResponseValidationError) ErrorName() string { return "GetChatResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetChatResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetChatResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetChatResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetChatResponseValidationError{}

// Validate checks the field values on GetLLMLimitsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLLMLimitsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLLMLimitsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLLMLimitsResponseMultiError, or nil if none found.
func (m *GetLLMLimitsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLLMLimitsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DailyLimit

	// no validation rules for Used

	// no validation rules for Reserved

	if len(errors) > 0 {
		return GetLLMLimitsResponseMultiError(errors)
	}

	return nil
}

// GetLLMLimitsResponseMultiError is an error wrapping multiple validation
// errors returned by GetLLMLimitsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetLLMLimitsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLLMLimitsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLLMLimitsResponseMultiError) AllErrors() []error { return m }

// GetLLMLimitsResponseValidationError is the validation error returned by
// GetLLMLimitsResponse.Validate if the designated constraints aren't met.
type GetLLMLimitsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLLMLimitsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLLMLimitsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLLMLimitsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLLMLimitsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLLMLimitsResponseValidationError) ErrorName() string {
	return "GetLLMLimitsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetLLMLimitsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLLMLimitsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLLMLimitsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLLMLimitsResponseValidationError{}

// Validate checks the field values on ChatStreamRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ChatStreamRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatStreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChatStreamRequestMultiError, or nil if none found.
func (m *ChatStreamRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatStreamRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Payload.(type) {
	case *ChatStreamRequest_SendMessage:
		if v == nil {
			err := ChatStreamRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSendMessage()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamRequestValidationError{
						field:  "SendMessage",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamRequestValidationError{
						field:  "SendMessage",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSendMessage()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamRequestValidationError{
					field:  "SendMessage",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamRequest_ToolDecision:
		if v == nil {
			err := ChatStreamRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToolDecision()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamRequestValidationError{
						field:  "ToolDecision",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamRequestValidationError{
						field:  "ToolDecision",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToolDecision()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamRequestValidationError{
					field:  "ToolDecision",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamRequest_Stop:
		if v == nil {
			err := ChatStreamRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetStop()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamRequestValidationError{
						field:  "Stop",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamRequestValidationError{
						field:  "Stop",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStop()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamRequestValidationError{
					field:  "Stop",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ChatStreamRequestMultiError(errors)
	}

	return nil
}

// ChatStreamRequestMultiError is an error wrapping multiple validation errors
// returned by ChatStreamRequest.ValidateAll() if the designated constraints
// aren't met.
type ChatStreamRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatStreamRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatStreamRequestMultiError) AllErrors() []error { return m }

// ChatStreamRequestValidationError is the validation error returned by
// ChatStreamRequest.Validate if the designated constraints aren't met.
type ChatStreamRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatStreamRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatStreamRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatStreamRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatStreamRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatStreamRequestValidationError) ErrorName() string {
	return "ChatStreamRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ChatStreamRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatStreamRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatStreamRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatStreamRequestValidationError{}

// Validate checks the field values on SendMessageAction with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendMessageAction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageAction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageActionMultiError, or nil if none found.
func (m *SendMessageAction) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageAction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetContent()) < 1 {
		err := SendMessageActionValidationError{
			field:  "Content",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ChatId != nil {
		// no validation rules for ChatId
	}

	if len(errors) > 0 {
		return SendMessageActionMultiError(errors)
	}

	return nil
}

// SendMessageActionMultiError is an error wrapping multiple validation errors
// returned by SendMessageAction.ValidateAll() if the designated constraints
// aren't met.
type SendMessageActionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageActionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageActionMultiError) AllErrors() []error { return m }

// SendMessageActionValidationError is the validation error returned by
// SendMessageAction.Validate if the designated constraints aren't met.
type SendMessageActionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageActionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageActionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageActionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageActionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageActionValidationError) ErrorName() string {
	return "SendMessageActionValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageActionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageAction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageActionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageActionValidationError{}

// Validate checks the field values on ToolDecisionAction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ToolDecisionAction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToolDecisionAction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ToolDecisionActionMultiError, or nil if none found.
func (m *ToolDecisionAction) ValidateAll() error {
	return m.validate(true)
}

func (m *ToolDecisionAction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetChatId()) < 1 {
		err := ToolDecisionActionValidationError{
			field:  "ChatId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetToolCallId()) < 1 {
		err := ToolDecisionActionValidationError{
			field:  "ToolCallId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Approve

	if len(errors) > 0 {
		return ToolDecisionActionMultiError(errors)
	}

	return nil
}

// ToolDecisionActionMultiError is an error wrapping multiple validation errors
// returned by ToolDecisionAction.ValidateAll() if the designated constraints
// aren't met.
type ToolDecisionActionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToolDecisionActionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToolDecisionActionMultiError) AllErrors() []error { return m }

// ToolDecisionActionValidationError is the validation error returned by
// ToolDecisionAction.Validate if the designated constraints aren't met.
type ToolDecisionActionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToolDecisionActionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToolDecisionActionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToolDecisionActionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToolDecisionActionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToolDecisionActionValidationError) ErrorName() string {
	return "ToolDecisionActionValidationError"
}

// Error satisfies the builtin error interface
func (e ToolDecisionActionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToolDecisionAction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToolDecisionActionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToolDecisionActionValidationError{}

// Validate checks the field values on StopAction with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StopAction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StopAction with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StopActionMultiError, or
// nil if none found.
func (m *StopAction) ValidateAll() error {
	return m.validate(true)
}

func (m *StopAction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return StopActionMultiError(errors)
	}

	return nil
}

// StopActionMultiError is an error wrapping multiple validation errors
// returned by StopAction.ValidateAll() if the designated constraints aren't met.
type StopActionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StopActionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StopActionMultiError) AllErrors() []error { return m }

// StopActionValidationError is the validation error returned by
// StopAction.Validate if the designated constraints aren't met.
type StopActionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StopActionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StopActionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StopActionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StopActionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StopActionValidationError) ErrorName() string { return "StopActionValidationError" }

// Error satisfies the builtin error interface
func (e StopActionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStopAction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StopActionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StopActionValidationError{}

// Validate checks the field values on ChatStreamResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ChatStreamResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatStreamResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChatStreamResponseMultiError, or nil if none found.
func (m *ChatStreamResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatStreamResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Event.(type) {
	case *ChatStreamResponse_Status:
		if v == nil {
			err := ChatStreamResponseValidationError{
				field:  "Event",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetStatus()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Status",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Status",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamResponse_Usage:
		if v == nil {
			err := ChatStreamResponseValidationError{
				field:  "Event",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetUsage()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Usage",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Usage",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamResponseValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamResponse_ContentDelta:
		if v == nil {
			err := ChatStreamResponseValidationError{
				field:  "Event",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetContentDelta()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "ContentDelta",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "ContentDelta",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetContentDelta()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamResponseValidationError{
					field:  "ContentDelta",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamResponse_ToolEvent:
		if v == nil {
			err := ChatStreamResponseValidationError{
				field:  "Event",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToolEvent()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "ToolEvent",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "ToolEvent",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToolEvent()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamResponseValidationError{
					field:  "ToolEvent",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamResponse_Final:
		if v == nil {
			err := ChatStreamResponseValidationError{
				field:  "Event",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFinal()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Final",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Final",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFinal()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamResponseValidationError{
					field:  "Final",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ChatStreamResponse_Error:
		if v == nil {
			err := ChatStreamResponseValidationError{
				field:  "Event",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetError()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamResponseValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetError()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamResponseValidationError{
					field:  "Error",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ChatStreamResponseMultiError(errors)
	}

	return nil
}

// ChatStreamResponseMultiError is an error wrapping multiple validation errors
// returned by ChatStreamResponse.ValidateAll() if the designated constraints
// aren't met.
type ChatStreamResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatStreamResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatStreamResponseMultiError) AllErrors() []error { return m }

// ChatStreamResponseValidationError is the validation error returned by
// ChatStreamResponse.Validate if the designated constraints aren't met.
type ChatStreamResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatStreamResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatStreamResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatStreamResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatStreamResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatStreamResponseValidationError) ErrorName() string {
	return "ChatStreamResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ChatStreamResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatStreamResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatStreamResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatStreamResponseValidationError{}

// Validate checks the field values on StatusEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StatusEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StatusEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StatusEventMultiError, or
// nil if none found.
func (m *StatusEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *StatusEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return StatusEventMultiError(errors)
	}

	return nil
}

// StatusEventMultiError is an error wrapping multiple validation errors
// returned by StatusEvent.ValidateAll() if the designated constraints aren't met.
type StatusEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StatusEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StatusEventMultiError) AllErrors() []error { return m }

// StatusEventValidationError is the validation error returned by
// StatusEvent.Validate if the designated constraints aren't met.
type StatusEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatusEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatusEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatusEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatusEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatusEventValidationError) ErrorName() string { return "StatusEventValidationError" }

// Error satisfies the builtin error interface
func (e StatusEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStatusEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatusEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatusEventValidationError{}

// Validate checks the field values on UsageEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UsageEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsageEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UsageEventMultiError, or
// nil if none found.
func (m *UsageEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *UsageEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUsage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageEventValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageEventValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageEventValidationError{
				field:  "Usage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UsageEventMultiError(errors)
	}

	return nil
}

// UsageEventMultiError is an error wrapping multiple validation errors
// returned by UsageEvent.ValidateAll() if the designated constraints aren't met.
type UsageEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsageEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsageEventMultiError) AllErrors() []error { return m }

// UsageEventValidationError is the validation error returned by
// UsageEvent.Validate if the designated constraints aren't met.
type UsageEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsageEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsageEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsageEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsageEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsageEventValidationError) ErrorName() string { return "UsageEventValidationError" }

// Error satisfies the builtin error interface
func (e UsageEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsageEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsageEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsageEventValidationError{}

// Validate checks the field values on ContentDeltaEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ContentDeltaEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ContentDeltaEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ContentDeltaEventMultiError, or nil if none found.
func (m *ContentDeltaEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *ContentDeltaEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Delta

	if len(errors) > 0 {
		return ContentDeltaEventMultiError(errors)
	}

	return nil
}

// ContentDeltaEventMultiError is an error wrapping multiple validation errors
// returned by ContentDeltaEvent.ValidateAll() if the designated constraints
// aren't met.
type ContentDeltaEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContentDeltaEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContentDeltaEventMultiError) AllErrors() []error { return m }

// ContentDeltaEventValidationError is the validation error returned by
// ContentDeltaEvent.Validate if the designated constraints aren't met.
type ContentDeltaEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContentDeltaEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContentDeltaEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContentDeltaEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContentDeltaEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContentDeltaEventValidationError) ErrorName() string {
	return "ContentDeltaEventValidationError"
}

// Error satisfies the builtin error interface
func (e ContentDeltaEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContentDeltaEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContentDeltaEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContentDeltaEventValidationError{}

// Validate checks the field values on FinalEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FinalEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FinalEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FinalEventMultiError, or
// nil if none found.
func (m *FinalEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *FinalEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FinalEventValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FinalEventValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FinalEventValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FinalEventMultiError(errors)
	}

	return nil
}

// FinalEventMultiError is an error wrapping multiple validation errors
// returned by FinalEvent.ValidateAll() if the designated constraints aren't met.
type FinalEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FinalEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FinalEventMultiError) AllErrors() []error { return m }

// FinalEventValidationError is the validation error returned by
// FinalEvent.Validate if the designated constraints aren't met.
type FinalEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FinalEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FinalEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FinalEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FinalEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FinalEventValidationError) ErrorName() string { return "FinalEventValidationError" }

// Error satisfies the builtin error interface
func (e FinalEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFinalEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FinalEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FinalEventValidationError{}

// Validate checks the field values on ErrorEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorEventMultiError, or
// nil if none found.
func (m *ErrorEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return ErrorEventMultiError(errors)
	}

	return nil
}

// ErrorEventMultiError is an error wrapping multiple validation errors
// returned by ErrorEvent.ValidateAll() if the designated constraints aren't met.
type ErrorEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorEventMultiError) AllErrors() []error { return m }

// ErrorEventValidationError is the validation error returned by
// ErrorEvent.Validate if the designated constraints aren't met.
type ErrorEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorEventValidationError) ErrorName() string { return "ErrorEventValidationError" }

// Error satisfies the builtin error interface
func (e ErrorEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorEventValidationError{}

// Validate checks the field values on ChatUsage with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatUsage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatUsage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatUsageMultiError, or nil
// if none found.
func (m *ChatUsage) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatUsage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PromptTokens

	// no validation rules for CompletionTokens

	// no validation rules for TotalTokens

	if len(errors) > 0 {
		return ChatUsageMultiError(errors)
	}

	return nil
}

// ChatUsageMultiError is an error wrapping multiple validation errors returned
// by ChatUsage.ValidateAll() if the designated constraints aren't met.
type ChatUsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatUsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatUsageMultiError) AllErrors() []error { return m }

// ChatUsageValidationError is the validation error returned by
// ChatUsage.Validate if the designated constraints aren't met.
type ChatUsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatUsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatUsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatUsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatUsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatUsageValidationError) ErrorName() string { return "ChatUsageValidationError" }

// Error satisfies the builtin error interface
func (e ChatUsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatUsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatUsageValidationError{}

// Validate checks the field values on ChatCompletion with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatCompletion) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatCompletion with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatCompletionMultiError,
// or nil if none found.
func (m *ChatCompletion) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatCompletion) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetChat()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChatCompletionValidationError{
					field:  "Chat",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChatCompletionValidationError{
					field:  "Chat",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChat()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChatCompletionValidationError{
				field:  "Chat",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatCompletionValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatCompletionValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatCompletionValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetUsage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChatCompletionValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChatCompletionValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChatCompletionValidationError{
				field:  "Usage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ChatCompletionMultiError(errors)
	}

	return nil
}

// ChatCompletionMultiError is an error wrapping multiple validation errors
// returned by ChatCompletion.ValidateAll() if the designated constraints
// aren't met.
type ChatCompletionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatCompletionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatCompletionMultiError) AllErrors() []error { return m }

// ChatCompletionValidationError is the validation error returned by
// ChatCompletion.Validate if the designated constraints aren't met.
type ChatCompletionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatCompletionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatCompletionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatCompletionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatCompletionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatCompletionValidationError) ErrorName() string { return "ChatCompletionValidationError" }

// Error satisfies the builtin error interface
func (e ChatCompletionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatCompletion.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatCompletionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatCompletionValidationError{}

// Validate checks the field values on ChatMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatMessageMultiError, or
// nil if none found.
func (m *ChatMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ChatId

	// no validation rules for Role

	// no validation rules for Content

	// no validation rules for ToolState

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChatMessageValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChatMessageValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChatMessageValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ToolName != nil {
		// no validation rules for ToolName
	}

	if m.ToolCallId != nil {
		// no validation rules for ToolCallId
	}

	if m.ToolArguments != nil {

		if all {
			switch v := interface{}(m.GetToolArguments()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatMessageValidationError{
						field:  "ToolArguments",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatMessageValidationError{
						field:  "ToolArguments",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToolArguments()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatMessageValidationError{
					field:  "ToolArguments",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.TokenUsage != nil {
		// no validation rules for TokenUsage
	}

	if m.Error != nil {
		// no validation rules for Error
	}

	if len(errors) > 0 {
		return ChatMessageMultiError(errors)
	}

	return nil
}

// ChatMessageMultiError is an error wrapping multiple validation errors
// returned by ChatMessage.ValidateAll() if the designated constraints aren't met.
type ChatMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatMessageMultiError) AllErrors() []error { return m }

// ChatMessageValidationError is the validation error returned by
// ChatMessage.Validate if the designated constraints aren't met.
type ChatMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatMessageValidationError) ErrorName() string { return "ChatMessageValidationError" }

// Error satisfies the builtin error interface
func (e ChatMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatMessageValidationError{}

// Validate checks the field values on ToolEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ToolEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToolEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ToolEventMultiError, or nil
// if none found.
func (m *ToolEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *ToolEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ToolName

	// no validation rules for ToolCallId

	// no validation rules for ArgsJson

	// no validation rules for State

	// no validation rules for Error

	if len(errors) > 0 {
		return ToolEventMultiError(errors)
	}

	return nil
}

// ToolEventMultiError is an error wrapping multiple validation errors returned
// by ToolEvent.ValidateAll() if the designated constraints aren't met.
type ToolEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToolEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToolEventMultiError) AllErrors() []error { return m }

// ToolEventValidationError is the validation error returned by
// ToolEvent.Validate if the designated constraints aren't met.
type ToolEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToolEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToolEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToolEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToolEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToolEventValidationError) ErrorName() string { return "ToolEventValidationError" }

// Error satisfies the builtin error interface
func (e ToolEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToolEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToolEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToolEventValidationError{}

// Validate checks the field values on MemoryFact with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MemoryFact) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoryFact with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MemoryFactMultiError, or
// nil if none found.
func (m *MemoryFact) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoryFact) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Content

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MemoryFactValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MemoryFactValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MemoryFactValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MemoryFactMultiError(errors)
	}

	return nil
}

// MemoryFactMultiError is an error wrapping multiple validation errors
// returned by MemoryFact.ValidateAll() if the designated constraints aren't met.
type MemoryFactMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoryFactMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoryFactMultiError) AllErrors() []error { return m }

// MemoryFactValidationError is the validation error returned by
// MemoryFact.Validate if the designated constraints aren't met.
type MemoryFactValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoryFactValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoryFactValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoryFactValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoryFactValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoryFactValidationError) ErrorName() string { return "MemoryFactValidationError" }

// Error satisfies the builtin error interface
func (e MemoryFactValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoryFact.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoryFactValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoryFactValidationError{}

// Validate checks the field values on ListMemoryFactsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMemoryFactsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMemoryFactsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMemoryFactsResponseMultiError, or nil if none found.
func (m *ListMemoryFactsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMemoryFactsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFacts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMemoryFactsResponseValidationError{
						field:  fmt.Sprintf("Facts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMemoryFactsResponseValidationError{
						field:  fmt.Sprintf("Facts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMemoryFactsResponseValidationError{
					field:  fmt.Sprintf("Facts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMemoryFactsResponseMultiError(errors)
	}

	return nil
}

// ListMemoryFactsResponseMultiError is an error wrapping multiple validation
// errors returned by ListMemoryFactsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListMemoryFactsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMemoryFactsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMemoryFactsResponseMultiError) AllErrors() []error { return m }

// ListMemoryFactsResponseValidationError is the validation error returned by
// ListMemoryFactsResponse.Validate if the designated constraints aren't met.
type ListMemoryFactsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMemoryFactsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMemoryFactsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMemoryFactsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMemoryFactsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMemoryFactsResponseValidationError) ErrorName() string {
	return "ListMemoryFactsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMemoryFactsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMemoryFactsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMemoryFactsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMemoryFactsResponseValidationError{}

// Validate checks the field values on CreateMemoryFactRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMemoryFactRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMemoryFactRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMemoryFactRequestMultiError, or nil if none found.
func (m *CreateMemoryFactRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMemoryFactRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetContent()); l < 1 || l > 200 {
		err := CreateMemoryFactRequestValidationError{
			field:  "Content",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateMemoryFactRequestMultiError(errors)
	}

	return nil
}

// CreateMemoryFactRequestMultiError is an error wrapping multiple validation
// errors returned by CreateMemoryFactRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateMemoryFactRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMemoryFactRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMemoryFactRequestMultiError) AllErrors() []error { return m }

// CreateMemoryFactRequestValidationError is the validation error returned by
// CreateMemoryFactRequest.Validate if the designated constraints aren't met.
type CreateMemoryFactRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMemoryFactRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMemoryFactRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMemoryFactRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMemoryFactRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMemoryFactRequestValidationError) ErrorName() string {
	return "CreateMemoryFactRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMemoryFactRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMemoryFactRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMemoryFactRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMemoryFactRequestValidationError{}

// Validate checks the field values on CreateMemoryFactResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMemoryFactResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMemoryFactResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMemoryFactResponseMultiError, or nil if none found.
func (m *CreateMemoryFactResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMemoryFactResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFact()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateMemoryFactResponseValidationError{
					field:  "Fact",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateMemoryFactResponseValidationError{
					field:  "Fact",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFact()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateMemoryFactResponseValidationError{
				field:  "Fact",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateMemoryFactResponseMultiError(errors)
	}

	return nil
}

// CreateMemoryFactResponseMultiError is an error wrapping multiple validation
// errors returned by CreateMemoryFactResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateMemoryFactResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMemoryFactResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMemoryFactResponseMultiError) AllErrors() []error { return m }

// CreateMemoryFactResponseValidationError is the validation error returned by
// CreateMemoryFactResponse.Validate if the designated constraints aren't met.
type CreateMemoryFactResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMemoryFactResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMemoryFactResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMemoryFactResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMemoryFactResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMemoryFactResponseValidationError) ErrorName() string {
	return "CreateMemoryFactResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMemoryFactResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMemoryFactResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMemoryFactResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMemoryFactResponseValidationError{}

// Validate checks the field values on DeleteMemoryFactRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMemoryFactRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMemoryFactRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMemoryFactRequestMultiError, or nil if none found.
func (m *DeleteMemoryFactRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMemoryFactRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := DeleteMemoryFactRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteMemoryFactRequestMultiError(errors)
	}

	return nil
}

// DeleteMemoryFactRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteMemoryFactRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteMemoryFactRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMemoryFactRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMemoryFactRequestMultiError) AllErrors() []error { return m }

// DeleteMemoryFactRequestValidationError is the validation error returned by
// DeleteMemoryFactRequest.Validate if the designated constraints aren't met.
type DeleteMemoryFactRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMemoryFactRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMemoryFactRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMemoryFactRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMemoryFactRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMemoryFactRequestValidationError) ErrorName() string {
	return "DeleteMemoryFactRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMemoryFactRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMemoryFactRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMemoryFactRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMemoryFactRequestValidationError{}
