// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: agent/agent.proto

package agent

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatStatus int32

const (
	ChatStatus_CHAT_STATUS_UNSPECIFIED ChatStatus = 0
	ChatStatus_CHAT_STATUS_ACTIVE      ChatStatus = 1
	ChatStatus_CHAT_STATUS_COMPLETED   ChatStatus = 2
	ChatStatus_CHAT_STATUS_FAILED      ChatStatus = 3
	ChatStatus_CHAT_STATUS_ARCHIVED    ChatStatus = 4
)

// Enum value maps for ChatStatus.
var (
	ChatStatus_name = map[int32]string{
		0: "CHAT_STATUS_UNSPECIFIED",
		1: "CHAT_STATUS_ACTIVE",
		2: "CHAT_STATUS_COMPLETED",
		3: "CHAT_STATUS_FAILED",
		4: "CHAT_STATUS_ARCHIVED",
	}
	ChatStatus_value = map[string]int32{
		"CHAT_STATUS_UNSPECIFIED": 0,
		"CHAT_STATUS_ACTIVE":      1,
		"CHAT_STATUS_COMPLETED":   2,
		"CHAT_STATUS_FAILED":      3,
		"CHAT_STATUS_ARCHIVED":    4,
	}
)

func (x ChatStatus) Enum() *ChatStatus {
	p := new(ChatStatus)
	*p = x
	return p
}

func (x ChatStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_agent_proto_enumTypes[0].Descriptor()
}

func (ChatStatus) Type() protoreflect.EnumType {
	return &file_agent_agent_proto_enumTypes[0]
}

func (x ChatStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatStatus.Descriptor instead.
func (ChatStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_SYSTEM      MessageRole = 1
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 2
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 3
	MessageRole_MESSAGE_ROLE_TOOL        MessageRole = 4
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_SYSTEM",
		2: "MESSAGE_ROLE_USER",
		3: "MESSAGE_ROLE_ASSISTANT",
		4: "MESSAGE_ROLE_TOOL",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_SYSTEM":      1,
		"MESSAGE_ROLE_USER":        2,
		"MESSAGE_ROLE_ASSISTANT":   3,
		"MESSAGE_ROLE_TOOL":        4,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_agent_proto_enumTypes[1].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_agent_agent_proto_enumTypes[1]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

type ToolCallStatus int32

const (
	ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED ToolCallStatus = 0
	ToolCallStatus_TOOL_CALL_STATUS_PENDING     ToolCallStatus = 1
	ToolCallStatus_TOOL_CALL_STATUS_EXECUTING   ToolCallStatus = 2
	ToolCallStatus_TOOL_CALL_STATUS_COMPLETED   ToolCallStatus = 3
	ToolCallStatus_TOOL_CALL_STATUS_FAILED      ToolCallStatus = 4
)

// Enum value maps for ToolCallStatus.
var (
	ToolCallStatus_name = map[int32]string{
		0: "TOOL_CALL_STATUS_UNSPECIFIED",
		1: "TOOL_CALL_STATUS_PENDING",
		2: "TOOL_CALL_STATUS_EXECUTING",
		3: "TOOL_CALL_STATUS_COMPLETED",
		4: "TOOL_CALL_STATUS_FAILED",
	}
	ToolCallStatus_value = map[string]int32{
		"TOOL_CALL_STATUS_UNSPECIFIED": 0,
		"TOOL_CALL_STATUS_PENDING":     1,
		"TOOL_CALL_STATUS_EXECUTING":   2,
		"TOOL_CALL_STATUS_COMPLETED":   3,
		"TOOL_CALL_STATUS_FAILED":      4,
	}
)

func (x ToolCallStatus) Enum() *ToolCallStatus {
	p := new(ToolCallStatus)
	*p = x
	return p
}

func (x ToolCallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_agent_proto_enumTypes[2].Descriptor()
}

func (ToolCallStatus) Type() protoreflect.EnumType {
	return &file_agent_agent_proto_enumTypes[2]
}

func (x ToolCallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolCallStatus.Descriptor instead.
func (ToolCallStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ListChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListChatsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListChatsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChatsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ListChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ListChatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListChatsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChatsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeleteChatRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// ===== Message Management =====
type StreamMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Pyaload:
	//
	//	*StreamMessageRequest_NewMessage
	Pyaload       isStreamMessageRequest_Pyaload `protobuf_oneof:"pyaload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageRequest) Reset() {
	*x = StreamMessageRequest{}
	mi := &file_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageRequest) ProtoMessage() {}

func (x *StreamMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageRequest.ProtoReflect.Descriptor instead.
func (*StreamMessageRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StreamMessageRequest) GetPyaload() isStreamMessageRequest_Pyaload {
	if x != nil {
		return x.Pyaload
	}
	return nil
}

func (x *StreamMessageRequest) GetNewMessage() *NewMessagePayload {
	if x != nil {
		if x, ok := x.Pyaload.(*StreamMessageRequest_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

type isStreamMessageRequest_Pyaload interface {
	isStreamMessageRequest_Pyaload()
}

type StreamMessageRequest_NewMessage struct {
	NewMessage *NewMessagePayload `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

func (*StreamMessageRequest_NewMessage) isStreamMessageRequest_Pyaload() {}

type NewMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        *string                `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessagePayload) Reset() {
	*x = NewMessagePayload{}
	mi := &file_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessagePayload) ProtoMessage() {}

func (x *NewMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessagePayload.ProtoReflect.Descriptor instead.
func (*NewMessagePayload) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *NewMessagePayload) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

func (x *NewMessagePayload) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *NewMessagePayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StreamMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamMessageResponse_Chunk
	//	*StreamMessageResponse_Message
	//	*StreamMessageResponse_ToolCall
	//	*StreamMessageResponse_Usage
	//	*StreamMessageResponse_Error
	//	*StreamMessageResponse_Chat
	Event         isStreamMessageResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageResponse) Reset() {
	*x = StreamMessageResponse{}
	mi := &file_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageResponse) ProtoMessage() {}

func (x *StreamMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageResponse.ProtoReflect.Descriptor instead.
func (*StreamMessageResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StreamMessageResponse) GetEvent() isStreamMessageResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamMessageResponse) GetChunk() *MessageChunk {
	if x != nil {
		if x, ok := x.Event.(*StreamMessageResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Event.(*StreamMessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetToolCall() *ToolCallEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamMessageResponse_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetUsage() *UsageEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamMessageResponse_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetChat() *ChatEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamMessageResponse_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isStreamMessageResponse_Event interface {
	isStreamMessageResponse_Event()
}

type StreamMessageResponse_Chunk struct {
	Chunk *MessageChunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type StreamMessageResponse_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type StreamMessageResponse_ToolCall struct {
	ToolCall *ToolCallEvent `protobuf:"bytes,3,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type StreamMessageResponse_Usage struct {
	Usage *UsageEvent `protobuf:"bytes,4,opt,name=usage,proto3,oneof"`
}

type StreamMessageResponse_Error struct {
	Error *ErrorEvent `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type StreamMessageResponse_Chat struct {
	Chat *ChatEvent `protobuf:"bytes,6,opt,name=chat,proto3,oneof"`
}

func (*StreamMessageResponse_Chunk) isStreamMessageResponse_Event() {}

func (*StreamMessageResponse_Message) isStreamMessageResponse_Event() {}

func (*StreamMessageResponse_ToolCall) isStreamMessageResponse_Event() {}

func (*StreamMessageResponse_Usage) isStreamMessageResponse_Event() {}

func (*StreamMessageResponse_Error) isStreamMessageResponse_Event() {}

func (*StreamMessageResponse_Chat) isStreamMessageResponse_Event() {}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetMessagesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetLLMLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyLimit    int32                  `protobuf:"varint,1,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	Used          int32                  `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMLimitsResponse) Reset() {
	*x = GetLLMLimitsResponse{}
	mi := &file_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMLimitsResponse) ProtoMessage() {}

func (x *GetLLMLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMLimitsResponse.ProtoReflect.Descriptor instead.
func (*GetLLMLimitsResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetLLMLimitsResponse) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *GetLLMLimitsResponse) GetUsed() int32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *GetLLMLimitsResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type Chat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentKey         string                 `protobuf:"bytes,4,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Status           ChatStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=llm_agent.api.agent.ChatStatus" json:"status,omitempty"`
	ParentChatId     string                 `protobuf:"bytes,7,opt,name=parent_chat_id,json=parentChatId,proto3" json:"parent_chat_id,omitempty"`               // для субагентов
	ParentToolCallId string                 `protobuf:"bytes,8,opt,name=parent_tool_call_id,json=parentToolCallId,proto3" json:"parent_tool_call_id,omitempty"` // связь с tool call родительского агента
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Chat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Chat) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chat) GetStatus() ChatStatus {
	if x != nil {
		return x.Status
	}
	return ChatStatus_CHAT_STATUS_UNSPECIFIED
}

func (x *Chat) GetParentChatId() string {
	if x != nil {
		return x.ParentChatId
	}
	return ""
}

func (x *Chat) GetParentToolCallId() string {
	if x != nil {
		return x.ParentToolCallId
	}
	return ""
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Role          MessageRole            `protobuf:"varint,3,opt,name=role,proto3,enum=llm_agent.api.agent.MessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"` // null для user, agent_key для агентов
	ToolCalls     []*ToolCall            `protobuf:"bytes,6,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,7,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // для tool результатов
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON string
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`       // JSON string (после выполнения)
	Status        ToolCallStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=llm_agent.api.agent.ToolCallStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetStatus() ToolCallStatus {
	if x != nil {
		return x.Status
	}
	return ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED
}

func (x *ToolCall) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ToolCall) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type MessageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageChunk) Reset() {
	*x = MessageChunk{}
	mi := &file_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChunk) ProtoMessage() {}

func (x *MessageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChunk.ProtoReflect.Descriptor instead.
func (*MessageChunk) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *MessageChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToolCallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEvent) Reset() {
	*x = ToolCallEvent{}
	mi := &file_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEvent) ProtoMessage() {}

func (x *ToolCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEvent.ProtoReflect.Descriptor instead.
func (*ToolCallEvent) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ToolCallEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallEvent) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCallEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UsageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         *ChatUsage             `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageEvent) Reset() {
	*x = UsageEvent{}
	mi := &file_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageEvent) ProtoMessage() {}

func (x *UsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageEvent.ProtoReflect.Descriptor instead.
func (*UsageEvent) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *UsageEvent) GetUsage() *ChatUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Отправляется при создании чата и при изменении имени
type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatName      string                 `protobuf:"bytes,2,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ChatEvent) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatEvent) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

type ChatUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatUsage) Reset() {
	*x = ChatUsage{}
	mi := &file_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUsage) ProtoMessage() {}

func (x *ChatUsage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUsage.ProtoReflect.Descriptor instead.
func (*ChatUsage) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ChatUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ChatUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ChatUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type MemoryFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryFact) Reset() {
	*x = MemoryFact{}
	mi := &file_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryFact) ProtoMessage() {}

func (x *MemoryFact) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryFact.ProtoReflect.Descriptor instead.
func (*MemoryFact) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *MemoryFact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryFact) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryFact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListMemoryFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*MemoryFact          `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoryFactsResponse) Reset() {
	*x = ListMemoryFactsResponse{}
	mi := &file_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoryFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoryFactsResponse) ProtoMessage() {}

func (x *ListMemoryFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoryFactsResponse.ProtoReflect.Descriptor instead.
func (*ListMemoryFactsResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ListMemoryFactsResponse) GetFacts() []*MemoryFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type CreateMemoryFactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryFactRequest) Reset() {
	*x = CreateMemoryFactRequest{}
	mi := &file_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryFactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryFactRequest) ProtoMessage() {}

func (x *CreateMemoryFactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryFactRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoryFactRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *CreateMemoryFactRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMemoryFactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fact          *MemoryFact            `protobuf:"bytes,1,opt,name=fact,proto3" json:"fact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryFactResponse) Reset() {
	*x = CreateMemoryFactResponse{}
	mi := &file_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryFactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryFactResponse) ProtoMessage() {}

func (x *CreateMemoryFactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryFactResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoryFactResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *CreateMemoryFactResponse) GetFact() *MemoryFact {
	if x != nil {
		return x.Fact
	}
	return nil
}

type DeleteMemoryFactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryFactRequest) Reset() {
	*x = DeleteMemoryFactRequest{}
	mi := &file_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryFactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryFactRequest) ProtoMessage() {}

func (x *DeleteMemoryFactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryFactRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryFactRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteMemoryFactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\x13llm_agent.api.agent\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"R\n" +
	"\x0eGetChatRequest\x12 \n" +
	"\achat_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06chatId\x12\x1e\n" +
	"\x06org_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05orgId\"@\n" +
	"\x0fGetChatResponse\x12-\n" +
	"\x04chat\x18\x01 \x01(\v2\x19.llm_agent.api.agent.ChatR\x04chat\"n\n" +
	"\x10ListChatsRequest\x12\x1e\n" +
	"\x06org_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05orgId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12&\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\bpageSize\"\x8b\x01\n" +
	"\x11ListChatsResponse\x12/\n" +
	"\x05chats\x18\x01 \x03(\v2\x19.llm_agent.api.agent.ChatR\x05chats\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"U\n" +
	"\x11DeleteChatRequest\x12 \n" +
	"\achat_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06chatId\x12\x1e\n" +
	"\x06org_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05orgId\"l\n" +
	"\x14StreamMessageRequest\x12I\n" +
	"\vnew_message\x18\x01 \x01(\v2&.llm_agent.api.agent.NewMessagePayloadH\x00R\n" +
	"newMessageB\t\n" +
	"\apyaload\"\x89\x01\n" +
	"\x11NewMessagePayload\x12%\n" +
	"\achat_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\x06chatId\x88\x01\x01\x12\x1e\n" +
	"\x06org_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05orgId\x12!\n" +
	"\acontent\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acontentB\n" +
	"\n" +
	"\b_chat_id\"\x80\x03\n" +
	"\x15StreamMessageResponse\x129\n" +
	"\x05chunk\x18\x01 \x01(\v2!.llm_agent.api.agent.MessageChunkH\x00R\x05chunk\x128\n" +
	"\amessage\x18\x02 \x01(\v2\x1c.llm_agent.api.agent.MessageH\x00R\amessage\x12A\n" +
	"\ttool_call\x18\x03 \x01(\v2\".llm_agent.api.agent.ToolCallEventH\x00R\btoolCall\x127\n" +
	"\x05usage\x18\x04 \x01(\v2\x1f.llm_agent.api.agent.UsageEventH\x00R\x05usage\x127\n" +
	"\x05error\x18\x05 \x01(\v2\x1f.llm_agent.api.agent.ErrorEventH\x00R\x05error\x124\n" +
	"\x04chat\x18\x06 \x01(\v2\x1e.llm_agent.api.agent.ChatEventH\x00R\x04chatB\a\n" +
	"\x05event\"\x8f\x01\n" +
	"\x12GetMessagesRequest\x12 \n" +
	"\achat_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06chatId\x12\x1e\n" +
	"\x06org_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05orgId\x12\x1f\n" +
	"\x05limit\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"e\n" +
	"\x13GetMessagesResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.llm_agent.api.agent.MessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"i\n" +
	"\x14GetLLMLimitsResponse\x12\x1f\n" +
	"\vdaily_limit\x18\x01 \x01(\x05R\n" +
	"dailyLimit\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x05R\x04used\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\"\x8f\x03\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tagent_key\x18\x04 \x01(\tR\bagentKey\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x127\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1f.llm_agent.api.agent.ChatStatusR\x06status\x12$\n" +
	"\x0eparent_chat_id\x18\a \x01(\tR\fparentChatId\x12-\n" +
	"\x13parent_tool_call_id\x18\b \x01(\tR\x10parentToolCallId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb5\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x124\n" +
	"\x04role\x18\x03 \x01(\x0e2 .llm_agent.api.agent.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12<\n" +
	"\n" +
	"tool_calls\x18\x06 \x03(\v2\x1d.llm_agent.api.agent.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\a \x01(\tR\n" +
	"toolCallId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9b\x02\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.llm_agent.api.agent.ToolCallStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"(\n" +
	"\fMessageChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"b\n" +
	"\rToolCallEvent\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"B\n" +
	"\n" +
	"UsageEvent\x124\n" +
	"\x05usage\x18\x01 \x01(\v2\x1e.llm_agent.api.agent.ChatUsageR\x05usage\":\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\tChatEvent\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tchat_name\x18\x02 \x01(\tR\bchatName\"\x80\x01\n" +
	"\tChatUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"q\n" +
	"\n" +
	"MemoryFact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"P\n" +
	"\x17ListMemoryFactsResponse\x125\n" +
	"\x05facts\x18\x01 \x03(\v2\x1f.llm_agent.api.agent.MemoryFactR\x05facts\"?\n" +
	"\x17CreateMemoryFactRequest\x12$\n" +
	"\acontent\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\acontent\"O\n" +
	"\x18CreateMemoryFactResponse\x123\n" +
	"\x04fact\x18\x01 \x01(\v2\x1f.llm_agent.api.agent.MemoryFactR\x04fact\"2\n" +
	"\x17DeleteMemoryFactRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id*\x8e\x01\n" +
	"\n" +
	"ChatStatus\x12\x1b\n" +
	"\x17CHAT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHAT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15CHAT_STATUS_COMPLETED\x10\x02\x12\x16\n" +
	"\x12CHAT_STATUS_FAILED\x10\x03\x12\x18\n" +
	"\x14CHAT_STATUS_ARCHIVED\x10\x04*\x8e\x01\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_ROLE_SYSTEM\x10\x01\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x03\x12\x15\n" +
	"\x11MESSAGE_ROLE_TOOL\x10\x04*\xad\x01\n" +
	"\x0eToolCallStatus\x12 \n" +
	"\x1cTOOL_CALL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aTOOL_CALL_STATUS_EXECUTING\x10\x02\x12\x1e\n" +
	"\x1aTOOL_CALL_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17TOOL_CALL_STATUS_FAILED\x10\x042\xbd\x05\n" +
	"\fAgentService\x12q\n" +
	"\aGetChat\x12#.llm_agent.api.agent.GetChatRequest\x1a$.llm_agent.api.agent.GetChatResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/chats/{chat_id}\x12m\n" +
	"\tListChats\x12%.llm_agent.api.agent.ListChatsRequest\x1a&.llm_agent.api.agent.ListChatsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/chats\x12i\n" +
	"\n" +
	"DeleteChat\x12&.llm_agent.api.agent.DeleteChatRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/chats/{chat_id}\x12\x86\x01\n" +
	"\vGetMessages\x12'.llm_agent.api.agent.GetMessagesRequest\x1a(.llm_agent.api.agent.GetMessagesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/chats/{chat_id}/messages\x12i\n" +
	"\fGetLLMLimits\x12\x16.google.protobuf.Empty\x1a).llm_agent.api.agent.GetLLMLimitsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/llm/limits\x12l\n" +
	"\rStreamMessage\x12).llm_agent.api.agent.StreamMessageRequest\x1a*.llm_agent.api.agent.StreamMessageResponse\"\x00(\x010\x012\x8a\x03\n" +
	"\rMemoryService\x12q\n" +
	"\x0fListMemoryFacts\x12\x16.google.protobuf.Empty\x1a,.llm_agent.api.agent.ListMemoryFactsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/memory/facts\x12\x8c\x01\n" +
	"\x10CreateMemoryFact\x12,.llm_agent.api.agent.CreateMemoryFactRequest\x1a-.llm_agent.api.agent.CreateMemoryFactResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/memory/facts\x12w\n" +
	"\x10DeleteMemoryFact\x12,.llm_agent.api.agent.DeleteMemoryFactRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/memory/facts/{id}B\xd4\x01\x92A\x9d\x01\x12>\n" +
	"\x0fLLM Service API\x12$API for LLM Service of BusinessThing2\x051.0.0\"\x04/api*\x02\x01\x022\x10application/json:\x10application/jsonZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z1llm-service/internal/pb/llm-agent/api/agent;agentb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_agent_agent_proto_goTypes = []any{
	(ChatStatus)(0),                  // 0: llm_agent.api.agent.ChatStatus
	(MessageRole)(0),                 // 1: llm_agent.api.agent.MessageRole
	(ToolCallStatus)(0),              // 2: llm_agent.api.agent.ToolCallStatus
	(*GetChatRequest)(nil),           // 3: llm_agent.api.agent.GetChatRequest
	(*GetChatResponse)(nil),          // 4: llm_agent.api.agent.GetChatResponse
	(*ListChatsRequest)(nil),         // 5: llm_agent.api.agent.ListChatsRequest
	(*ListChatsResponse)(nil),        // 6: llm_agent.api.agent.ListChatsResponse
	(*DeleteChatRequest)(nil),        // 7: llm_agent.api.agent.DeleteChatRequest
	(*StreamMessageRequest)(nil),     // 8: llm_agent.api.agent.StreamMessageRequest
	(*NewMessagePayload)(nil),        // 9: llm_agent.api.agent.NewMessagePayload
	(*StreamMessageResponse)(nil),    // 10: llm_agent.api.agent.StreamMessageResponse
	(*GetMessagesRequest)(nil),       // 11: llm_agent.api.agent.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 12: llm_agent.api.agent.GetMessagesResponse
	(*GetLLMLimitsResponse)(nil),     // 13: llm_agent.api.agent.GetLLMLimitsResponse
	(*Chat)(nil),                     // 14: llm_agent.api.agent.Chat
	(*Message)(nil),                  // 15: llm_agent.api.agent.Message
	(*ToolCall)(nil),                 // 16: llm_agent.api.agent.ToolCall
	(*MessageChunk)(nil),             // 17: llm_agent.api.agent.MessageChunk
	(*ToolCallEvent)(nil),            // 18: llm_agent.api.agent.ToolCallEvent
	(*UsageEvent)(nil),               // 19: llm_agent.api.agent.UsageEvent
	(*ErrorEvent)(nil),               // 20: llm_agent.api.agent.ErrorEvent
	(*ChatEvent)(nil),                // 21: llm_agent.api.agent.ChatEvent
	(*ChatUsage)(nil),                // 22: llm_agent.api.agent.ChatUsage
	(*MemoryFact)(nil),               // 23: llm_agent.api.agent.MemoryFact
	(*ListMemoryFactsResponse)(nil),  // 24: llm_agent.api.agent.ListMemoryFactsResponse
	(*CreateMemoryFactRequest)(nil),  // 25: llm_agent.api.agent.CreateMemoryFactRequest
	(*CreateMemoryFactResponse)(nil), // 26: llm_agent.api.agent.CreateMemoryFactResponse
	(*DeleteMemoryFactRequest)(nil),  // 27: llm_agent.api.agent.DeleteMemoryFactRequest
	(*timestamppb.Timestamp)(nil),    // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 29: google.protobuf.Empty
}
var file_agent_agent_proto_depIdxs = []int32{
	14, // 0: llm_agent.api.agent.GetChatResponse.chat:type_name -> llm_agent.api.agent.Chat
	14, // 1: llm_agent.api.agent.ListChatsResponse.chats:type_name -> llm_agent.api.agent.Chat
	9,  // 2: llm_agent.api.agent.StreamMessageRequest.new_message:type_name -> llm_agent.api.agent.NewMessagePayload
	17, // 3: llm_agent.api.agent.StreamMessageResponse.chunk:type_name -> llm_agent.api.agent.MessageChunk
	15, // 4: llm_agent.api.agent.StreamMessageResponse.message:type_name -> llm_agent.api.agent.Message
	18, // 5: llm_agent.api.agent.StreamMessageResponse.tool_call:type_name -> llm_agent.api.agent.ToolCallEvent
	19, // 6: llm_agent.api.agent.StreamMessageResponse.usage:type_name -> llm_agent.api.agent.UsageEvent
	20, // 7: llm_agent.api.agent.StreamMessageResponse.error:type_name -> llm_agent.api.agent.ErrorEvent
	21, // 8: llm_agent.api.agent.StreamMessageResponse.chat:type_name -> llm_agent.api.agent.ChatEvent
	15, // 9: llm_agent.api.agent.GetMessagesResponse.messages:type_name -> llm_agent.api.agent.Message
	0,  // 10: llm_agent.api.agent.Chat.status:type_name -> llm_agent.api.agent.ChatStatus
	28, // 11: llm_agent.api.agent.Chat.created_at:type_name -> google.protobuf.Timestamp
	28, // 12: llm_agent.api.agent.Chat.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 13: llm_agent.api.agent.Message.role:type_name -> llm_agent.api.agent.MessageRole
	16, // 14: llm_agent.api.agent.Message.tool_calls:type_name -> llm_agent.api.agent.ToolCall
	28, // 15: llm_agent.api.agent.Message.created_at:type_name -> google.protobuf.Timestamp
	2,  // 16: llm_agent.api.agent.ToolCall.status:type_name -> llm_agent.api.agent.ToolCallStatus
	28, // 17: llm_agent.api.agent.ToolCall.created_at:type_name -> google.protobuf.Timestamp
	28, // 18: llm_agent.api.agent.ToolCall.completed_at:type_name -> google.protobuf.Timestamp
	22, // 19: llm_agent.api.agent.UsageEvent.usage:type_name -> llm_agent.api.agent.ChatUsage
	28, // 20: llm_agent.api.agent.MemoryFact.created_at:type_name -> google.protobuf.Timestamp
	23, // 21: llm_agent.api.agent.ListMemoryFactsResponse.facts:type_name -> llm_agent.api.agent.MemoryFact
	23, // 22: llm_agent.api.agent.CreateMemoryFactResponse.fact:type_name -> llm_agent.api.agent.MemoryFact
	3,  // 23: llm_agent.api.agent.AgentService.GetChat:input_type -> llm_agent.api.agent.GetChatRequest
	5,  // 24: llm_agent.api.agent.AgentService.ListChats:input_type -> llm_agent.api.agent.ListChatsRequest
	7,  // 25: llm_agent.api.agent.AgentService.DeleteChat:input_type -> llm_agent.api.agent.DeleteChatRequest
	11, // 26: llm_agent.api.agent.AgentService.GetMessages:input_type -> llm_agent.api.agent.GetMessagesRequest
	29, // 27: llm_agent.api.agent.AgentService.GetLLMLimits:input_type -> google.protobuf.Empty
	8,  // 28: llm_agent.api.agent.AgentService.StreamMessage:input_type -> llm_agent.api.agent.StreamMessageRequest
	29, // 29: llm_agent.api.agent.MemoryService.ListMemoryFacts:input_type -> google.protobuf.Empty
	25, // 30: llm_agent.api.agent.MemoryService.CreateMemoryFact:input_type -> llm_agent.api.agent.CreateMemoryFactRequest
	27, // 31: llm_agent.api.agent.MemoryService.DeleteMemoryFact:input_type -> llm_agent.api.agent.DeleteMemoryFactRequest
	4,  // 32: llm_agent.api.agent.AgentService.GetChat:output_type -> llm_agent.api.agent.GetChatResponse
	6,  // 33: llm_agent.api.agent.AgentService.ListChats:output_type -> llm_agent.api.agent.ListChatsResponse
	29, // 34: llm_agent.api.agent.AgentService.DeleteChat:output_type -> google.protobuf.Empty
	12, // 35: llm_agent.api.agent.AgentService.GetMessages:output_type -> llm_agent.api.agent.GetMessagesResponse
	13, // 36: llm_agent.api.agent.AgentService.GetLLMLimits:output_type -> llm_agent.api.agent.GetLLMLimitsResponse
	10, // 37: llm_agent.api.agent.AgentService.StreamMessage:output_type -> llm_agent.api.agent.StreamMessageResponse
	24, // 38: llm_agent.api.agent.MemoryService.ListMemoryFacts:output_type -> llm_agent.api.agent.ListMemoryFactsResponse
	26, // 39: llm_agent.api.agent.MemoryService.CreateMemoryFact:output_type -> llm_agent.api.agent.CreateMemoryFactResponse
	29, // 40: llm_agent.api.agent.MemoryService.DeleteMemoryFact:output_type -> google.protobuf.Empty
	32, // [32:41] is the sub-list for method output_type
	23, // [23:32] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	file_agent_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*StreamMessageRequest_NewMessage)(nil),
	}
	file_agent_agent_proto_msgTypes[6].OneofWrappers = []any{}
	file_agent_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamMessageResponse_Chunk)(nil),
		(*StreamMessageResponse_Message)(nil),
		(*StreamMessageResponse_ToolCall)(nil),
		(*StreamMessageResponse_Usage)(nil),
		(*StreamMessageResponse_Error)(nil),
		(*StreamMessageResponse_Chat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		EnumInfos:         file_agent_agent_proto_enumTypes,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
